defaults:
  - train_diffusion_transformer_real_hybrid_dino_multi_gpu_workspace
  - _self_
  - override task: maniskill_pick

device_ids: '0'

training:
  num_epochs: 50
  checkpoint_every: 5
  val_every: 1
  rollout_every: 50
  sample_every: 5
  gradient_accumulate_every: 4

policy:
  obs_encoder:
    img_size: 224

dataloader:
  batch_size: 4
  num_workers: 1
  persistent_workers: True
  prefetch_factor: 2

val_dataloader:
  batch_size: 4
  num_workers: 1
  persistent_workers: True
  prefetch_factor: 2

logging:
  project: maniskill_armada
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${..name}_${..task_name}
  tags: ["maniskill", "pickcube", "poc"]
