name: maniskill_pick
image_shape: [3, 224, 224]
dataset_path: /home/stu4/armada_data/maniskill_pick

shape_meta: &shape_meta
  obs:
    wrist_img:
      shape: ${....image_shape}
      type: rgb
    side_img:
      shape: ${....image_shape}
      type: rgb
    ee_pose:
      shape: [9]    # [x, y, z, rot_6d[0:6]]
      type: low_dim
      rotation_rep: rotation_6d
  action:
    shape: [10]     # [x, y, z, rot_6d[0:6], gripper]
    rotation_rep: rotation_6d

dataset:
  _target_: diffusion_policy.dataset.mydataset.MyDataset
  zarr_path: ${....dataset_path}/replay_buffer.zarr
  horizon: 16
  pad_before: 1
  pad_after: 14
  n_obs_steps: 2
  shape_meta: *shape_meta
  random_crop: True
  color_jitter: True
  image_shape: ${....image_shape}
  max_train_episodes: null
